#name: mlops_template_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

#pool:
#  name: Demo123

trigger:
 branches:
   include:
     - release*
pr:
  branches:
    include:
      - main 

resources:
  repositories:
    - repository: ResTrig 
      type: github
      name: KIRTHISHKT/MainYaml
      endpoint: 'github.com_KIRTHISHKT'
      #ref: '$(Build.SourceBranch)' 
    - repository: yamltemplate
      type: github
      name: KIRTHISHKT/yamltemplate
      endpoint: 'github.com_KIRTHISHKT'
      ref: main


stages:
  - template: stages.yml@yamltemplate  # Template reference kirthish
