#name: mlops_template_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

#pool:
#  name: Demo123

trigger:
 branches:
   include:
     - release*
pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: yamltemp
      type: github
      name: KIRTHISHKT/yamltemplate
      endpoint: KIRTHISHKT
      ref: main
    - repository: ResTrig
      type: github
      name: KIRTHISHKT/MainYaml
      endpoint: KIRTHISHKT
      ref: '$(Build.SourceBranch)' 

extends:
  template: stage123.yml@yamltemp  # Template reference 
